"""Added hash

Revision ID: 4c437d6ac588
Revises: 8b8aba019bfb
Create Date: 2023-12-30 13:20:48.522560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c437d6ac588'
down_revision: Union[str, None] = '8b8aba019bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'hash')
    # ### end Alembic commands ###
