"""models changed id added

Revision ID: 8b584e1353c1
Revises: 1ea46c44378b
Create Date: 2023-12-18 20:16:59.356752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b584e1353c1'
down_revision: Union[str, None] = '1ea46c44378b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_id',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['hashtags.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hashtag_id',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_id',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['hashtags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('category_product_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'product_id')
    op.drop_constraint('hashtags_product_id_fkey', 'hashtags', type_='foreignkey')
    op.drop_column('hashtags', 'product_id')
    op.drop_constraint('topic_product_id_fkey', 'topic', type_='foreignkey')
    op.drop_column('topic', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('topic_product_id_fkey', 'topic', 'product', ['product_id'], ['id'])
    op.add_column('hashtags', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('hashtags_product_id_fkey', 'hashtags', 'product', ['product_id'], ['id'])
    op.add_column('category', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('category_product_id_fkey', 'category', 'product', ['product_id'], ['id'])
    op.drop_table('topic_id')
    op.drop_table('hashtag_id')
    op.drop_table('category_id')
    # ### end Alembic commands ###
